from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 613)
        MainWindow.setMinimumSize(QtCore.QSize(380, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_count = QtWidgets.QPushButton(self.centralwidget)
        self.btn_count.setMinimumSize(QtCore.QSize(0, 35))
        self.btn_count.setMaximumSize(QtCore.QSize(16777215, 35))
        self.btn_count.setObjectName("btn_count")
        self.gridLayout.addWidget(self.btn_count, 7, 0, 1, 3)
        self.label_choose = QtWidgets.QLabel(self.centralwidget)
        self.label_choose.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_choose.setObjectName("label_choose")
        self.gridLayout.addWidget(self.label_choose, 1, 0, 1, 3)
        self.btn_browse = QtWidgets.QToolButton(self.centralwidget)
        self.btn_browse.setMinimumSize(QtCore.QSize(0, 20))
        self.btn_browse.setMaximumSize(QtCore.QSize(50, 20))
        self.btn_browse.setBaseSize(QtCore.QSize(0, 0))
        self.btn_browse.setObjectName("btn_browse")
        self.gridLayout.addWidget(self.btn_browse, 2, 2, 1, 1)
        self.label_counting_result = QtWidgets.QLabel(self.centralwidget)
        self.label_counting_result.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_counting_result.setObjectName("label_counting_result")
        self.gridLayout.addWidget(self.label_counting_result, 10, 1, 1, 1)
        self.label_photographed = QtWidgets.QLabel(self.centralwidget)
        self.label_photographed.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_photographed.setObjectName("label_photographed")
        self.gridLayout.addWidget(self.label_photographed, 10, 0, 1, 1)
        self.line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit.setEnabled(True)
        self.line_edit.setMinimumSize(QtCore.QSize(0, 20))
        self.line_edit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.line_edit.setObjectName("line_edit")
        self.gridLayout.addWidget(self.line_edit, 2, 0, 1, 2)
        self.c_box_counter = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c_box_counter.sizePolicy().hasHeightForWidth())
        self.c_box_counter.setSizePolicy(sizePolicy)
        self.c_box_counter.setMaximumSize(QtCore.QSize(200, 16777215))
        self.c_box_counter.setObjectName("c_box_counter")
        self.gridLayout.addWidget(self.c_box_counter, 5, 0, 1, 1)
        self.label_singles = QtWidgets.QLabel(self.centralwidget)
        self.label_singles.setMinimumSize(QtCore.QSize(0, 13))
        self.label_singles.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_singles.setObjectName("label_singles")
        self.gridLayout.addWidget(self.label_singles, 11, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 1)
        self.list_view_sets = QtWidgets.QListWidget(self.centralwidget)
        self.list_view_sets.setMinimumSize(QtCore.QSize(0, 100))
        self.list_view_sets.setMaximumSize(QtCore.QSize(16777215, 100))
        self.list_view_sets.setObjectName("list_view_sets")
        self.gridLayout.addWidget(self.list_view_sets, 15, 1, 2, 2)
        self.label_sets = QtWidgets.QLabel(self.centralwidget)
        self.label_sets.setMinimumSize(QtCore.QSize(0, 13))
        self.label_sets.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_sets.setWordWrap(True)
        self.label_sets.setObjectName("label_sets")
        self.gridLayout.addWidget(self.label_sets, 15, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 3)
        self.progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_bar.sizePolicy().hasHeightForWidth())
        self.progress_bar.setSizePolicy(sizePolicy)
        self.progress_bar.setMinimumSize(QtCore.QSize(0, 10))
        self.progress_bar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.progress_bar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.progress_bar.setObjectName("progress_bar")
        self.gridLayout.addWidget(self.progress_bar, 8, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 17, 1, 1, 1)
        self.list_view_singles = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.list_view_singles.sizePolicy().hasHeightForWidth())
        self.list_view_singles.setSizePolicy(sizePolicy)
        self.list_view_singles.setMinimumSize(QtCore.QSize(0, 200))
        self.list_view_singles.setObjectName("list_view_singles")
        self.gridLayout.addWidget(self.list_view_singles, 11, 1, 3, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 14, 1, 1, 1)
        self.c_box_list = QtWidgets.QCheckBox(self.centralwidget)
        self.c_box_list.setObjectName("c_box_list")
        self.gridLayout.addWidget(self.c_box_list, 6, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 380, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.actionImport_list_as_PDF = QtWidgets.QAction(MainWindow)
        self.actionImport_list_as_PDF.setObjectName("actionImport_list_as_PDF")
        self.menuFile.addAction(self.actionImport_list_as_PDF)
        self.menuAbout.addAction(self.actionInfo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_count.setText(_translate("MainWindow", "count"))
        self.label_choose.setText(_translate("MainWindow", "Choose folder to browse (with or without subfolders):"))
        self.btn_browse.setText(_translate("MainWindow", "..."))
        self.label_counting_result.setText(_translate("MainWindow", "TextLabel"))
        self.label_photographed.setText(_translate("MainWindow", "Photographed objects:"))
        self.c_box_counter.setText(_translate("MainWindow", "display counter result"))
        self.label_singles.setText(_translate("MainWindow", "List of objects:"))
        self.label_sets.setText(_translate("MainWindow", "List of objects in sets:"))
        self.c_box_list.setText(_translate("MainWindow", "display list of objects"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))
        self.actionImport_list_as_PDF.setText(_translate("MainWindow", "Import list..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
